### ISSUE TITLE
client env setting

### ISSUE THREAD

**Issue by naamoonoo** [woowa-techcamp-2020/hkb-2#1]
## Describe the feature
- 클라이언트 개발 환경 설정

## Todo
- [x] webpack, babel config 파일 설정
- [x] prettier, eslint 설정
- [x] 폴더 구조 설정
