### ISSUE TITLE
DB 설정

### ISSUE THREAD

**Issue by parkjihwanjay** [woowa-techcamp-2020/hkb-2#17]
## Describe the feature
- DB의 기본적인 설정을 마친다.

## Todo
- [x] aws EC2에 EC2 인스턴스 생성
- [x] mysql 설치 및 세션 생성
- [x] ERD에 따른 Table 생성
- [x] MysqlWorkBrench와 연결

**Comment by naamoonoo** [comment]
다했슴미당
