### ISSUE TITLE
[client] 로그인 & 회원가입 테스트

### ISSUE THREAD

**Issue by parkjihwanjay** [woowa-techcamp-2020/hkb-2#47]
## Describe the feature
- 회원가입 후 로그인 테스트

## Todo
- [ ] 쿠키에 sessionId가 잘 담기는지 확인
- [x] 회원가입 이후 로그인이 성공되는지 확인

**Comment by parkjihwanjay** [comment]
클라이언트 쿠키에 sessionId가 담기지 않기 때문에 쿠키를 설정해주는 로직 추가 필요

- [ ] 클라이언트 쿠키 설정
