### ISSUE TITLE
카테고리 fetch

### ISSUE THREAD

**Issue by naamoonoo** [woowa-techcamp-2020/hkb-2#52]
## Describe the feature
- 거래내역을 추가할때 선택지로 보여줄 카테고리를 fetch할 수 있게 api설정 및 icon_name 컬럼 추가

## Todo
- [x] add new column in db
- [x] get categories service, repository, router setup server
- [x] fetch api in client
- [x] fetch and show in `AddNewTransaciton` component
