### ISSUE TITLE
relational Database with payment and user id

### ISSUE THREAD

**Issue by naamoonoo** [woowa-techcamp-2020/hkb-2#58]
## Describe the feature
- `payment_user_method` db 추가 생성 및 해당 router and api 구현 

## Todo
- [x] database table 추가(user_id, payment_id를 FK로 받는 m:n관계의 테이블)
- [x] payment 관련 CRUD method 구현, repository, router, service
- [x] payment 관련 ajax request용 api 구현 for client
