### ISSUE TITLE
[client][통계] 막대 그래프 구현

### ISSUE THREAD

**Issue by parkjihwanjay** [woowa-techcamp-2020/hkb-2#60]
## Describe the feature
- 모든 지출 카테고리에 대해 막대그래프가 그려진다.

## Todo
- [x] 비율이 높은 항목의 카테고리부터 내림차순으로 표시된다.
- [x] 지출 카테고리 이름, 퍼센트, 금액이 함께 표시된다.
- [ ] 애니메이션 효과와 함께 차트가 그려진다. (선택)
