### ISSUE TITLE
스토어 정비 및 데이터 핸들링

### ISSUE THREAD

**Issue by naamoonoo** [woowa-techcamp-2020/hkb-2#70]
## Describe the feature
- visiblity 스토어 추가 및 해당 필터에 따른 transaction 필터링

## Todo
- [x] visibilty store 추가
- [x] header visibility filter selector 추가
- [x] visibilty store 변경에 따른 데이터 필터링
