### ISSUE TITLE
data handling

### ISSUE THREAD

**Issue by naamoonoo** [woowa-techcamp-2020/hkb-2#74]
## Describe the feature
- 월 변경에 따른 transaction 데이터 다시 fetch

## Todo
- [X] connectAction: 데이터가 아니라 액션만 필요한 경우에 컴포넌트가 해당 api로 스토어와 연결, 이 경우에는 액션이 실행되어도 데이터를 해당컴포넌트 내에서 사용하고 있지 않기 때문에 새로 render할 필요가 없음, connectStore와 분리를 통해 더 효율적인 데이터 관리가 가능해짐
- [X] store -> connectAction 케이스에 따라 새로렌더링할 컴포넌트를 받지 않는 경우를 따로 분리
- [X] Sidebar -> 월 데이터를 변경할 때, 해당 월에 따라 transaction 데이터에 따라 데이터를 다시 fetch
- [X] Icon -> 굳이 필요치 않은 Props를 제거
- [X] transactionStore -> get fetch의 parameter가 변함에 따라, 해당 포멧에 맞게 수정
